# Generated by Django 5.0.2 on 2025-11-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_alter_customer_id_alter_feedback_id_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='brand',
        ),
    ]
